In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(
    "dataset/Community Healthcare MultiSymptomsDisease Diagnostic Dataset.csv"
)

In [3]:
df.head()

,disease,symptom_cough,symptom_dry_cough,symptom_productive_cough,symptom_shortness_of_breath,symptom_wheezing,symptom_chest_tightness,symptom_sore_throat,symptom_runny_nose,symptom_nasal_congestion,...,rare_symptom_tall_stature_rare,rare_symptom_hyperextensible_skin_rare,rare_symptom_joint_hypermobility_rare,rare_symptom_macroglossia_rare,rare_symptom_hearing_loss_early_onset_rare,rare_symptom_developmental_delay_rare,rare_symptom_proximal_muscle_weakness_rare,rare_symptom_bulbar_symptoms_rare,rare_symptom_respiratory_failure_rare,rare_symptom_renal_cysts_rare
0,Hyperthyroidism,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Coronary_Artery_Disease,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Irritable_Bowel_Syndrome,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Irritable_Bowel_Syndrome,0,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,Obesity,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.shape

(100000, 175)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 175 entries, disease to rare_symptom_renal_cysts_rare
dtypes: int64(174), str(1)
memory usage: 134.7 MB

In [6]:
df.isnull().sum().sort_values(ascending=False)

disease                                    0
symptom_shortness_of_breath_on_exertion    0
symptom_digital_ulcers                     0
symptom_skin_thickening                    0
symptom_telangiectasia                     0
                                          ..
symptom_heartburn                          0
symptom_loss_of_appetite                   0
symptom_gi_bleeding                        0
symptom_dark_stools                        0
rare_symptom_renal_cysts_rare              0
Length: 175, dtype: int64

In [7]:
df['disease'].value_counts()

disease
Asthma                           21295
Hyperthyroidism                  10747
Irritable_Bowel_Syndrome          9023
Obesity                           7853
Pneumonia                         6493
Peptic_Ulcer_Disease              5834
Type2_Diabetes                    5239
Chronic_Kidney_Disease            4993
Gastritis                         4431
Osteoarthritis                    4264
Flu                               3444
Depression                        2321
Common_Cold                       2236
COPD                              2060
COVID19                           2033
Polycystic_Ovary_Syndrome         1820
Hypothyroidism                    1683
Hypertension                      1647
Coronary_Artery_Disease            922
Migraine                           467
Epilepsy                           366
Cystic_Fibrosis                    164
Systemic_Lupus_Erythematosus       156
Generalized_Anxiety_Disorder        95
Tuberculosis                        67
Stroke                              64
Amyotrophic_Lateral_Sclerosis       50
Osteopetrosis                       46
Marfan_Syndrome                     29
Ehlers_Danlos_Syndrome              24
Cirrhosis                           18
Spinal_Muscular_Atrophy             17
Dengue                              17
Inflammatory_Bowel_Disease          14
Niemann_Pick_Disease                14
Gaucher_Disease                     12
Multiple_Sclerosis                  12
Ulcerative_Colitis                   7
Chronic_Liver_Disease                5
Crohn_Disease                        4
Fanconi_Anemia                       4
Acute_Gastroenteritis                3
Typhoid_Fever                        2
Psoriasis                            2
Urinary_Tract_Infection              2
Metabolic_Syndrome                   1
Name: count, dtype: int64

In [8]:
disease_counts = df['disease'].value_counts()

valid_diseases = disease_counts[disease_counts >= 100].index

df = df[df['disease'].isin(valid_diseases)]

In [9]:
df.shape

(99491, 175)

In [10]:
df['disease'].value_counts()

disease
Asthma                          21295
Hyperthyroidism                 10747
Irritable_Bowel_Syndrome         9023
Obesity                          7853
Pneumonia                        6493
Peptic_Ulcer_Disease             5834
Type2_Diabetes                   5239
Chronic_Kidney_Disease           4993
Gastritis                        4431
Osteoarthritis                   4264
Flu                              3444
Depression                       2321
Common_Cold                      2236
COPD                             2060
COVID19                          2033
Polycystic_Ovary_Syndrome        1820
Hypothyroidism                   1683
Hypertension                     1647
Coronary_Artery_Disease           922
Migraine                          467
Epilepsy                          366
Cystic_Fibrosis                   164
Systemic_Lupus_Erythematosus      156
Name: count, dtype: int64

In [11]:
df.isnull().sum().sum()

np.int64(0)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes.value_counts()

int64    174
str        1
Name: count, dtype: int64

In [14]:
X = df.drop('disease', axis=1)

y = df['disease']

In [15]:
X.shape, y.shape

((99491, 174), (99491,))

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [17]:
X_train.shape, X_test.shape

((79592, 174), (19899, 174))

In [18]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [19]:
y_pred = model.predict(X_test)

In [20]:

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy =", accuracy)
print("Accuracy Percentage =", accuracy * 100, "%")

Accuracy = 0.4352982561937786
Accuracy Percentage = 43.52982561937786 %

In [21]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                              precision    recall  f1-score   support

                      Asthma       0.41      0.84      0.55      4259
                        COPD       0.68      0.15      0.25       412
                     COVID19       0.45      0.09      0.15       407
      Chronic_Kidney_Disease       0.49      0.31      0.38       999
                 Common_Cold       0.54      0.12      0.19       447
     Coronary_Artery_Disease       0.52      0.09      0.15       184
             Cystic_Fibrosis       1.00      0.03      0.06        33
                  Depression       0.52      0.17      0.26       464
                    Epilepsy       0.80      0.05      0.10        73
                         Flu       0.47      0.27      0.34       689
                   Gastritis       0.49      0.34      0.40       886
                Hypertension       0.49      0.06      0.11       329
             Hyperthyroidism       0.43      0.53      0.48      2149
              Hypothyroidism       0.43      0.12      0.19       337
    Irritable_Bowel_Syndrome       0.42      0.36      0.39      1805
                    Migraine       1.00      0.01      0.02        93
                     Obesity       0.44      0.52      0.48      1571
              Osteoarthritis       0.44      0.19      0.27       853
        Peptic_Ulcer_Disease       0.50      0.47      0.48      1167
                   Pneumonia       0.46      0.32      0.38      1299
   Polycystic_Ovary_Syndrome       0.43      0.13      0.20       364
Systemic_Lupus_Erythematosus       0.00      0.00      0.00        31
              Type2_Diabetes       0.50      0.18      0.26      1048

                    accuracy                           0.44     19899
                   macro avg       0.52      0.23      0.26     19899
                weighted avg       0.46      0.44      0.40     19899

C:\Users\veer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\veer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\veer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [1]:
print(df.columns.tolist())

NameError: name 'df' is not defined

In [22]:
from sklearn.ensemble import RandomForestClassifier

balanced_model = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

balanced_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [23]:
y_pred_balanced = balanced_model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy =", accuracy_score(y_test, y_pred_balanced) * 100, "%")

print(classification_report(
    y_test,
    y_pred_balanced,
    zero_division=0
))

Accuracy = 40.49449721091512 %
                              precision    recall  f1-score   support

                      Asthma       0.65      0.38      0.48      4259
                        COPD       0.34      0.42      0.38       412
                     COVID19       0.32      0.32      0.32       407
      Chronic_Kidney_Disease       0.39      0.46      0.42       999
                 Common_Cold       0.30      0.45      0.36       447
     Coronary_Artery_Disease       0.28      0.36      0.32       184
             Cystic_Fibrosis       0.84      0.97      0.90        33
                  Depression       0.30      0.46      0.36       464
                    Epilepsy       0.25      0.68      0.37        73
                         Flu       0.31      0.50      0.38       689
                   Gastritis       0.31      0.52      0.39       886
                Hypertension       0.31      0.39      0.34       329
             Hyperthyroidism       0.49      0.32      0.39      2149
              Hypothyroidism       0.23      0.51      0.31       337
    Irritable_Bowel_Syndrome       0.46      0.28      0.35      1805
                    Migraine       0.36      0.32      0.34        93
                     Obesity       0.44      0.46      0.45      1571
              Osteoarthritis       0.35      0.40      0.38       853
        Peptic_Ulcer_Disease       0.42      0.56      0.48      1167
                   Pneumonia       0.40      0.38      0.39      1299
   Polycystic_Ovary_Syndrome       0.27      0.48      0.35       364
Systemic_Lupus_Erythematosus       0.38      0.19      0.26        31
              Type2_Diabetes       0.37      0.37      0.37      1048

                    accuracy                           0.40     19899
                   macro avg       0.38      0.44      0.39     19899
                weighted avg       0.45      0.40      0.41     19899

In [24]:
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

In [25]:
random_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(
        class_weight='balanced',
        random_state=42,
        n_jobs=-1
    ),
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring='f1_macro',
    random_state=42,
    n_jobs=-1,
    verbose=2
)

random_search.fit(X_train, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3,
                   estimator=RandomForestClassifier(class_weight='balanced',
                                                    n_jobs=-1,
                                                    random_state=42),
                   n_jobs=-1,
                   param_distributions={'max_depth': [10, 20, 30, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300]},
                   random_state=42, scoring='f1_macro', verbose=2)

In [26]:
random_search.best_params_

{'n_estimators': 100,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 30}

In [27]:
best_model = random_search.best_estimator_

y_pred_best = best_model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy =", accuracy_score(y_test, y_pred_best) * 100, "%")

print(classification_report(
    y_test,
    y_pred_best,
    zero_division=0
))

Accuracy = 36.50434695210814 %
                              precision    recall  f1-score   support

                      Asthma       0.68      0.31      0.43      4259
                        COPD       0.30      0.42      0.35       412
                     COVID19       0.28      0.34      0.31       407
      Chronic_Kidney_Disease       0.39      0.38      0.39       999
                 Common_Cold       0.24      0.41      0.30       447
     Coronary_Artery_Disease       0.17      0.53      0.26       184
             Cystic_Fibrosis       0.85      1.00      0.92        33
                  Depression       0.29      0.47      0.36       464
                    Epilepsy       0.16      0.73      0.26        73
                         Flu       0.29      0.44      0.35       689
                   Gastritis       0.31      0.47      0.37       886
                Hypertension       0.24      0.42      0.30       329
             Hyperthyroidism       0.51      0.26      0.35      2149
              Hypothyroidism       0.16      0.50      0.24       337
    Irritable_Bowel_Syndrome       0.45      0.21      0.29      1805
                    Migraine       0.11      0.48      0.17        93
                     Obesity       0.43      0.41      0.42      1571
              Osteoarthritis       0.36      0.37      0.36       853
        Peptic_Ulcer_Disease       0.40      0.53      0.45      1167
                   Pneumonia       0.41      0.35      0.38      1299
   Polycystic_Ovary_Syndrome       0.23      0.55      0.32       364
Systemic_Lupus_Erythematosus       0.19      0.35      0.24        31
              Type2_Diabetes       0.37      0.37      0.37      1048

                    accuracy                           0.37     19899
                   macro avg       0.34      0.45      0.36     19899
                weighted avg       0.44      0.37      0.37     19899

In [29]:
df.groupby('disease')[X.columns].mean()

,symptom_cough,symptom_dry_cough,symptom_productive_cough,symptom_shortness_of_breath,symptom_wheezing,symptom_chest_tightness,symptom_sore_throat,symptom_runny_nose,symptom_nasal_congestion,symptom_sinus_pain,...,rare_symptom_tall_stature_rare,rare_symptom_hyperextensible_skin_rare,rare_symptom_joint_hypermobility_rare,rare_symptom_macroglossia_rare,rare_symptom_hearing_loss_early_onset_rare,rare_symptom_developmental_delay_rare,rare_symptom_proximal_muscle_weakness_rare,rare_symptom_bulbar_symptoms_rare,rare_symptom_respiratory_failure_rare,rare_symptom_renal_cysts_rare
disease,,,,,,,,,,,,,,,,,,,,,
Asthma,0.231932,0.211364,0.230524,0.195210,0.200610,0.217422,0.229960,0.252219,0.228833,0.193801,...,0.001080,0.001550,0.001737,0.002301,0.002771,0.003099,0.000986,0.001550,0.003146,0.000892
COPD,0.215534,0.212136,0.236408,0.246602,0.294175,0.239806,0.247573,0.188350,0.209709,0.227184,...,0.001456,0.001942,0.000971,0.003398,0.005825,0.002913,0.000000,0.000485,0.005340,0.000485
COVID19,0.369405,0.259223,0.229218,0.212494,0.215937,0.233153,0.253812,0.238564,0.218888,0.232661,...,0.001968,0.002951,0.000984,0.001968,0.001968,0.003935,0.000492,0.000000,0.000984,0.002459
Chronic_Kidney_Disease,0.344482,0.310835,0.305227,0.413379,0.472061,0.398358,0.357501,0.296215,0.339876,0.398758,...,0.003204,0.004406,0.001001,0.004406,0.001602,0.001803,0.000200,0.001202,0.000801,0.000401
Common_Cold,0.392665,0.398479,0.524150,0.363148,0.376118,0.384168,0.429338,0.437388,0.388640,0.295617,...,0.000894,0.003131,0.000447,0.001342,0.001342,0.004025,0.000000,0.002236,0.002683,0.001789
Coronary_Artery_Disease,0.182213,0.055315,0.056399,0.057484,0.087852,0.120390,0.078091,0.058568,0.114967,0.077007,...,0.001085,0.001085,0.001085,0.001085,0.003254,0.007592,0.002169,0.001085,0.004338,0.000000
Cystic_Fibrosis,0.292683,0.329268,0.298780,0.304878,0.304878,0.304878,0.304878,0.280488,0.280488,0.323171,...,0.000000,0.000000,0.006098,0.000000,0.000000,0.006098,0.000000,0.006098,0.000000,0.000000
Depression,0.237398,0.218009,0.238259,0.202068,0.307626,0.297286,0.246015,0.246445,0.177510,0.217579,...,0.000431,0.005170,0.001723,0.003447,0.001293,0.000862,0.000000,0.003016,0.002585,0.000431
Epilepsy,0.377049,0.327869,0.368852,0.390710,0.404372,0.415301,0.341530,0.393443,0.390710,0.374317,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002732,0.000000,0.002732
Flu,0.195993,0.167828,0.188153,0.165796,0.164344,0.211963,0.201800,0.209640,0.215157,0.202671,...,0.001452,0.003775,0.000290,0.002033,0.000581,0.001161,0.000581,0.001742,0.002033,0.001161
Gastritis,0.207402,0.175807,0.191830,0.245317,0.215978,0.173099,0.159332,0.176484,0.209208,0.221169,...,0.001128,0.002483,0.000226,0.001805,0.001354,0.005191,0.001354,0.002257,0.001580,0.002031
Hypertension,0.206436,0.150577,0.192471,0.170006,0.175471,0.179114,0.187614,0.181542,0.206436,0.172435,...,0.001214,0.001821,0.000000,0.002429,0.002429,0.002429,0.000607,0.000607,0.000607,0.003643
Hyperthyroidism,0.205732,0.220248,0.223225,0.212431,0.217363,0.206197,0.165907,0.202103,0.200893,0.225830,...,0.000465,0.003257,0.000651,0.002140,0.001210,0.001675,0.000372,0.002326,0.001861,0.000744
Hypothyroidism,0.086750,0.128936,0.138443,0.139632,0.083185,0.128342,0.171123,0.117053,0.106952,0.158645,...,0.002377,0.005348,0.002971,0.001188,0.002971,0.000594,0.001783,0.001783,0.002377,0.002377
Irritable_Bowel_Syndrome,0.200709,0.265654,0.273634,0.243046,0.238058,0.219328,0.223872,0.280062,0.173667,0.248033,...,0.000997,0.002217,0.000776,0.001662,0.002771,0.005320,0.000997,0.002106,0.002327,0.002882
Migraine,0.053533,0.055675,0.036403,0.070664,0.053533,0.036403,0.066381,0.087794,0.025696,0.092077,...,0.006424,0.002141,0.002141,0.002141,0.002141,0.000000,0.000000,0.002141,0.004283,0.000000
Obesity,0.417802,0.414491,0.394372,0.415892,0.451675,0.402649,0.450656,0.400484,0.430791,0.418948,...,0.001401,0.001783,0.000764,0.002037,0.001146,0.002547,0.001019,0.001528,0.003056,0.000764
Osteoarthritis,0.302298,0.359522,0.264775,0.343809,0.265713,0.273218,0.262195,0.225610,0.353189,0.268762,...,0.000704,0.002580,0.001407,0.000235,0.000938,0.001173,0.000235,0.001173,0.002814,0.000938
Peptic_Ulcer_Disease,0.207405,0.164210,0.182893,0.218546,0.190607,0.223003,0.198492,0.184093,0.212547,0.227974,...,0.002057,0.001543,0.001200,0.002743,0.001371,0.002914,0.001885,0.000857,0.002400,0.001543
Pneumonia,0.367627,0.404436,0.316033,0.419837,0.338364,0.387494,0.393655,0.369937,0.340675,0.401355,...,0.002310,0.001848,0.001078,0.001232,0.001078,0.002772,0.000616,0.001848,0.001540,0.000924
Polycystic_Ovary_Syndrome,0.076923,0.119231,0.106044,0.087912,0.079121,0.114835,0.076923,0.129121,0.113187,0.097802,...,0.000549,0.002747,0.000549,0.004945,0.001099,0.005495,0.000000,0.002198,0.001099,0.000549
Systemic_Lupus_Erythematosus,0.346154,0.346154,0.358974,0.288462,0.557692,0.365385,0.333333,0.307692,0.410256,0.384615,...,0.006410,0.000000,0.000000,0.006410,0.012821,0.000000,0.000000,0.000000,0.006410,0.000000
Type2_Diabetes,0.221225,0.246994,0.256728,0.206910,0.211682,0.253865,0.264554,0.232105,0.300630,0.233632,...,0.002291,0.001145,0.000382,0.001718,0.001145,0.001145,0.000573,0.001909,0.001718,0.002100

In [30]:
X.sum(axis=1).describe()

count    99491.000000
mean        28.485481
std         13.480336
min          1.000000
25%         19.000000
50%         27.000000
75%         37.000000
max         97.000000
dtype: float64

In [31]:
from sklearn.ensemble import ExtraTreesClassifier

extra_model = ExtraTreesClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

extra_model.fit(X_train, y_train)

extra_pred = extra_model.predict(X_test)

print(
    "Accuracy =",
    accuracy_score(y_test, extra_pred) * 100,
    "%"
)

print(
    classification_report(
        y_test,
        extra_pred,
        zero_division=0
    )
)

Accuracy = 42.750892004623346 %
                              precision    recall  f1-score   support

                      Asthma       0.37      0.82      0.51      4259
                        COPD       0.60      0.23      0.34       412
                     COVID19       0.50      0.16      0.25       407
      Chronic_Kidney_Disease       0.53      0.30      0.38       999
                 Common_Cold       0.59      0.19      0.29       447
     Coronary_Artery_Disease       0.52      0.16      0.25       184
             Cystic_Fibrosis       0.86      0.91      0.88        33
                  Depression       0.51      0.23      0.32       464
                    Epilepsy       0.50      0.22      0.30        73
                         Flu       0.49      0.30      0.37       689
                   Gastritis       0.52      0.32      0.40       886
                Hypertension       0.57      0.16      0.24       329
             Hyperthyroidism       0.42      0.47      0.44      2149
              Hypothyroidism       0.46      0.14      0.21       337
    Irritable_Bowel_Syndrome       0.47      0.29      0.36      1805
                    Migraine       0.47      0.09      0.15        93
                     Obesity       0.44      0.48      0.46      1571
              Osteoarthritis       0.55      0.24      0.33       853
        Peptic_Ulcer_Disease       0.52      0.46      0.49      1167
                   Pneumonia       0.51      0.31      0.38      1299
   Polycystic_Ovary_Syndrome       0.44      0.20      0.28       364
Systemic_Lupus_Erythematosus       0.00      0.00      0.00        31
              Type2_Diabetes       0.51      0.16      0.24      1048

                    accuracy                           0.43     19899
                   macro avg       0.49      0.30      0.34     19899
                weighted avg       0.47      0.43      0.40     19899

In [32]:
from sklearn.ensemble import HistGradientBoostingClassifier

hgb_model = HistGradientBoostingClassifier(
    max_iter=200,
    learning_rate=0.1,
    random_state=42
)

hgb_model.fit(X_train, y_train)

hgb_pred = hgb_model.predict(X_test)

print(
    "Accuracy =",
    accuracy_score(y_test, hgb_pred) * 100,
    "%"
)

print(
    classification_report(
        y_test,
        hgb_pred,
        zero_division=0
    )
)

Accuracy = 55.90733202673501 %
                              precision    recall  f1-score   support

                      Asthma       0.56      0.78      0.65      4259
                        COPD       0.54      0.40      0.46       412
                     COVID19       0.51      0.33      0.40       407
      Chronic_Kidney_Disease       0.57      0.49      0.53       999
                 Common_Cold       0.63      0.39      0.48       447
     Coronary_Artery_Disease       0.46      0.34      0.39       184
             Cystic_Fibrosis       0.42      0.91      0.57        33
                  Depression       0.55      0.41      0.47       464
                    Epilepsy       0.18      0.27      0.22        73
                         Flu       0.57      0.45      0.50       689
                   Gastritis       0.55      0.53      0.54       886
                Hypertension       0.55      0.35      0.43       329
             Hyperthyroidism       0.58      0.63      0.60      2149
              Hypothyroidism       0.45      0.31      0.37       337
    Irritable_Bowel_Syndrome       0.56      0.50      0.53      1805
                    Migraine       0.32      0.29      0.30        93
                     Obesity       0.57      0.57      0.57      1571
              Osteoarthritis       0.54      0.45      0.49       853
        Peptic_Ulcer_Disease       0.62      0.60      0.61      1167
                   Pneumonia       0.60      0.51      0.55      1299
   Polycystic_Ovary_Syndrome       0.48      0.32      0.38       364
Systemic_Lupus_Erythematosus       0.04      0.19      0.06        31
              Type2_Diabetes       0.62      0.46      0.53      1048

                    accuracy                           0.56     19899
                   macro avg       0.50      0.46      0.46     19899
                weighted avg       0.56      0.56      0.55     19899

In [33]:
from sklearn.model_selection import RandomizedSearchCV

hgb_params = {
    'learning_rate': [0.05, 0.1, 0.2],
    'max_iter': [100, 200, 300],
    'max_leaf_nodes': [15, 31, 63],
    'max_depth': [None, 10, 20],
    'min_samples_leaf': [10, 20, 30]
}

In [34]:
hgb_search = RandomizedSearchCV(
    estimator=HistGradientBoostingClassifier(
        random_state=42
    ),
    param_distributions=hgb_params,
    n_iter=10,
    cv=3,
    scoring='f1_macro',
    random_state=42,
    n_jobs=-1,
    verbose=2
)

hgb_search.fit(X_train, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3,
                   estimator=HistGradientBoostingClassifier(random_state=42),
                   n_jobs=-1,
                   param_distributions={'learning_rate': [0.05, 0.1, 0.2],
                                        'max_depth': [None, 10, 20],
                                        'max_iter': [100, 200, 300],
                                        'max_leaf_nodes': [15, 31, 63],
                                        'min_samples_leaf': [10, 20, 30]},
                   random_state=42, scoring='f1_macro', verbose=2)

In [35]:
hgb_search.best_params_

{'min_samples_leaf': 10,
 'max_leaf_nodes': 63,
 'max_iter': 100,
 'max_depth': None,
 'learning_rate': 0.05}

In [36]:
best_hgb_model = hgb_search.best_estimator_

hgb_best_pred = best_hgb_model.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score, classification_report

print(
    "Accuracy =",
    accuracy_score(y_test, hgb_best_pred) * 100,
    "%"
)

print(
    classification_report(
        y_test,
        hgb_best_pred,
        zero_division=0
    )
)

Accuracy = 60.43017237047088 %
                              precision    recall  f1-score   support

                      Asthma       0.61      0.81      0.70      4259
                        COPD       0.57      0.44      0.50       412
                     COVID19       0.57      0.38      0.46       407
      Chronic_Kidney_Disease       0.60      0.54      0.57       999
                 Common_Cold       0.64      0.44      0.52       447
     Coronary_Artery_Disease       0.60      0.35      0.44       184
             Cystic_Fibrosis       0.84      0.97      0.90        33
                  Depression       0.60      0.44      0.50       464
                    Epilepsy       0.39      0.40      0.39        73
                         Flu       0.62      0.51      0.56       689
                   Gastritis       0.59      0.55      0.57       886
                Hypertension       0.61      0.35      0.44       329
             Hyperthyroidism       0.61      0.69      0.65      2149
              Hypothyroidism       0.49      0.32      0.39       337
    Irritable_Bowel_Syndrome       0.60      0.57      0.58      1805
                    Migraine       0.42      0.25      0.31        93
                     Obesity       0.60      0.62      0.61      1571
              Osteoarthritis       0.60      0.50      0.54       853
        Peptic_Ulcer_Disease       0.65      0.64      0.64      1167
                   Pneumonia       0.61      0.56      0.58      1299
   Polycystic_Ovary_Syndrome       0.57      0.37      0.44       364
Systemic_Lupus_Erythematosus       0.15      0.13      0.14        31
              Type2_Diabetes       0.63      0.53      0.57      1048

                    accuracy                           0.60     19899
                   macro avg       0.57      0.49      0.52     19899
                weighted avg       0.60      0.60      0.60     19899

In [38]:
import pickle

with open("healthcare_model.pkl", "wb") as file:
    pickle.dump(best_hgb_model, file)

In [39]:
with open("symptom_features.pkl", "wb") as file:
    pickle.dump(list(X.columns), file)

In [2]:
print(df.columns.tolist())

NameError: name 'df' is not defined

In [ ]:
import pandas as pd